### PR TITLE
Add lz4 compression

### LINKED ISSUE #17: Add LZ4 compression
LZ4 compression is not there
LZ4 decompression share frame specs with ZSTD. 
Skippable frames are same in both ZSTD and LZ4, making impossible to detect file type.
It should be combined LZ4/ZSTD decompressor to properly handle skippable frames at the beginning and middle of a file.

### LINKED ISSUE #18: ZSTD compressed file is not recognized if starts with skippable frame
When zstd compressed file starts with skippable frame, file is not recognized as ZSTD

### LINKED ISSUE #19: ZSTD decompressor exit prematurely  on multi-frame file, without decompressing whole file
When zstd file contains multiple frames, decompressor erroneously detect EOF condition on end of first frame and exist without an error, and not decompressing whole file.

### PR DESCRIPTION
**Pull request by scherepanov**
Fixes #17
Fixes #18
Fixes #19

### CODE REVIEW

**Comment by salcock** [comment]
Sorry for taking so long to look at this. This is a very helpful contribution -- thanks a lot!

One question: you appear to have removed the old ior-zstd.c file in favour of the ior-zstd-lz4.c file -- is this going to cause problems for anyone who wants to read zstd files but doesn't happen to have liblz4 available at compile time?

What should probably happen is that there should be two branches in create_io_reader() when deciding which open function to call for a zstd file, e.g. something like

    #if HAVE_LIBZSTD
    #if HAVE_LIBLZ4
        io = zstd_lz4_open(io);
    #else
        io = zstd_open(io);
    #endif
    #else
        fprintf(stderr, "error message etc.....");
        return NULL;
    #endif

**Comment by scherepanov** [comment]
From what I remember, I did independent lz4 and zest inclusion. I.e. if lz4 there, but no zstd, or reverse, or both are present/absent, everything will be compiled properly and will be able to handle corresponding set of compression algos.
Commit was a while ago - 2 month, and I do not remember what I did two days ago. I can look more on my code and confirm if this is correct.
And, of course, I do have it running in production.

**Comment by scherepanov** [comment]
I look on a code, and reader correctly being opened.

i.e. if zstd is present but no lz4 at compile time, file correctly will be opened for zest only.
It is due to fact that both compressions was developed by the same guy, and they share framing standard, allow for correct execution of compression out of frame magic number.
So, if file have compression that libwandio has not been compiled with, reader will throw run-time error.

**Comment by salcock** [comment]
Ok, that's cool. I had a closer look at ior-zstd-lz4.c and it looks like the right decisions are being made in there. Just thought I'd double check with you to make sure you had the situation covered :)

I'll run some extra tests on my own as well and then I'll work on merging this in officially. Thanks for your help.

**Comment by salcock** [comment]
Merged into the develop branch (5edcb48c06834db2809ef3d33afcc6d111705325), so this is now staged for the next wandio release.

**Pull request closed without merging**
